# Generated by Django 5.2.17 on 2026-10-06 19:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_item_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('confirmado', 'Confirmado')], default='criado', max_length=20)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_processados', to='repositories.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome_item', models.CharField(max_length=200)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_itens', to='repositories.item')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='repositories.pedido')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('usuario', 'idempotency_key'), name='uq_pedido_usuario_idempotency'),
        ),
        migrations.AddIndex(
            model_name='eventoprocessado',
            index=models.Index(fields=['event_id'], name='ix_evento_processado_event_id'),
        ),
        migrations.AddIndex(
            model_name='eventoprocessado',
            index=models.Index(fields=['processado_em'], name='ix_evento_processado_data'),
        ),
        migrations.AddConstraint(
            model_name='eventoprocessado',
            constraint=models.UniqueConstraint(fields=('event_type', 'idempotency_key'), name='uq_evento_processado_tipo_chave'),
        ),
    ]
