# Generated by Django 5.2.17 on 2026-10-08 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='criado', max_length=20),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='repositories.pedido')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='repositories.pedido')),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao', to='repositories.pagamento')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
